### USER ROUTES
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Bob",
  "email": "bob@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "password"
}

### CAPSTONE ROUTES
### Index
GET http://localhost:3000/capstones

###SHOW
GET http://localhost:3000/capstones/2

### DELETE
DELETE http://localhost:3000/capstones/1

###CREATE
POST http://localhost:3000/capstones
Content-Type: application/json

{
  "name" : "Pacman2",
  "description": "Video Game",
  "url": "google.com" 
}
###UPDATE
PATCH http://localhost:3000/capstones/2
Content-Type: application/json

{
  "name" : "Example",
  "description": "Video Game",
  "url": "google.com"
} 

###STUDENTS ROUTES
### STUDENT INDEX
GET http://localhost:3000/students

### STUDENT SHOW
GET http://localhost:3000/students/1

### STUDENT UPDATE
PATCH http://localhost:3000/students/1
Content-Type: application/json

{
  "first_name": "Paul"
}

### STUDENT CREATE
POST http://localhost:3000/students
Content-Type: application/json

{
  "first_name": "test"
}

### STUDENT DESTROY
DELETE http://localhost:3000/students/4

### STUDENT current
GET http://localhost:3000/students/current
Content-Type: application/json

### SKILL ROUTES
### Index
GET http://localhost:3000/skills

###SHOW
GET http://localhost:3000/skills/2

### DELETE
DELETE http://localhost:3000/skills/2

###CREATE
POST http://localhost:3000/skills
Content-Type: application/json

{
  "name" : "C++"
}
###UPDATE
PATCH http://localhost:3000/skills/3
Content-Type: application/json

{
  "name" : "C#"
} 


### EXPERIENCE ROUTES
### Index
GET http://localhost:3000/experiences

###SHOW
GET http://localhost:3000/experiences/1

### DELETE
DELETE http://localhost:3000/experiences/3

###CREATE
POST http://localhost:3000/experiences
Content-Type: application/json

{
  "start": "2023-05-11",
  "end": "2023-06-16",
  "title": "Crew Member",
  "company": "FOODGUYS2",
  "details": "Served something"
}
###UPDATE
PATCH http://localhost:3000/experiences/3
Content-Type: application/json

{
  "start": "2023-05-11",
  "end": "2023-06-16",
  "title": "Crew Member",
  "company": "Jumbo",
  "details": "Served something"
}

### EDUCATIONS ROUTES
### Index
GET http://localhost:3000/educations

###SHOW
GET http://localhost:3000/educations/1

### DELETE
DELETE http://localhost:3000/educations/3

###CREATE
POST http://localhost:3000/educations
Content-Type: application/json

{
  "start": "2023-05-11",
  "end": "2023-06-16",
  "degree": "Physics",
  "university": "UTA",
  "details": "Physics degree"
}
###UPDATE
PATCH http://localhost:3000/educations/4
Content-Type: application/json

{
  "start": "2023-05-11",
  "end": "2023-06-16",
  "degree": "Electrical Engineering",
  "university": "Cambodia University",
  "details": "Changed to Electrical Engineering"
}

### RESUMES ROUTES
### INDEX
GET http://localhost:3000/resumes.json

### SHOW
GET http://localhost:3000/resume/1.json