### USER ROUTES
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### CAPSTONE ROUTES
### Index
GET http://localhost:3000/capstone

###SHOW
GET http://localhost:3000/capstone/2

### DELETE
DELETE http://localhost:3000/capstone/1

###CREATE
POST http://localhost:3000/capstone/new
Content-Type: application/json

{
  "name" : "Pacman",
  "description": "Video Game",
  "url": "google.com" 
}
###UPDATE
PATCH http://localhost:3000/capstone/2
Content-Type: application/json

{
  "name" : "Example",
  "description": "Video Game",
  "url": "google.com"
} 

### STUDENT INDEX
GET http://localhost:3000/students.json

### STUDENT Show
GET http://localhost:3000/students/1.json

### STUDENT UPDATE
PATCH http://localhost:3000/students/1.json 
Content-Type: application/json

{
  "first_name": "Fred"
}

### STUDENT CREATE
POST http://localhost:3000/students.json
Content-Type: application/json

{
  "first_name": "test"
}

### STUDENT DESTROY
DELETE http://localhost:3000/students/1.json

### SKILL ROUTES
### Index
GET http://localhost:3000/skill

###SHOW
GET http://localhost:3000/skill/2

### DELETE
DELETE http://localhost:3000/skill/2

###CREATE
POST http://localhost:3000/skill/new
Content-Type: application/json

{
  "name" : "C++"
}
###UPDATE
PATCH http://localhost:3000/skill/3
Content-Type: application/json

{
  "name" : "C#"
} 


### EXPERIENCE ROUTES
### Index
GET http://localhost:3000/experience

###SHOW
GET http://localhost:3000/experience/1

### DELETE
DELETE http://localhost:3000/experience/3

###CREATE
POST http://localhost:3000/experience/new
Content-Type: application/json

{
  "start": "2023-05-11",
  "end": "2023-06-16",
  "title": "Crew Member",
  "company": "FOODGUYS",
  "details": "Served something"
}
###UPDATE
PATCH http://localhost:3000/experience/3
Content-Type: application/json

{
  "start": "2023-05-11",
  "end": "2023-06-16",
  "title": "Crew Member",
  "company": "Jumbo",
  "details": "Served something"
}